<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SkkmNugetSample</RootNamespace>
    <AssemblyTitle>Демо SkkmConnector</AssemblyTitle>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
    <ApplicationIcon>Assets\skkmconnector-cs-icon.ico</ApplicationIcon>
    <!-- Копировать XML-документацию коннектора в вывод — для тултипов <summary> в демо -->
    <CopyDocumentationFilesFromPackages>true</CopyDocumentationFilesFromPackages>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.0.10" />
    <PackageReference Include="Avalonia.Desktop" Version="11.0.10" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.0.10" />
    <PackageReference Include="Material.Icons.Avalonia" Version="2.1.10" />
    <PackageReference Include="SkkmConnector" Version="1.26.1" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
    <Content Include="Examples\**\*.cs" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
